name: Clear Cache
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
env:
  PROD_REPOS: nesi/support-docs nesi/research-developer-cloud nesi/agdr-docs nesi/nesi-mkdoc-template MattBixley/eri-support-docs afasfaffsa/sadsadasdf
  GH_TOKEN: ${{ github.token }}
jobs: 
  get-targets:
    outputs:
      targets: ${{ steps.get-targets.outputs.targets }}
    runs-on: ubuntu-latest
    steps:
    - name: Get active PR Branches
      id: get-targets
      run: |
          targets=""
          for repo in $PROD_REPOS;do
            branches="$(for pr in $(gh pr list --repo ${repo} --json headRefName | jq -r '.[].headRefName'); do printf "${pr} "; done)" \
            || echo "::warning:: Could not read from ${repo}" \
            && ( echo "::notice:: Open Valid Merge Requests in ${repo}: ${branches}"; \
            for branch in ${branches};do targets="${targets} ${repo}:${branch}";done )
          done
          echo $targets
          echo "targets=${targets}" >> $GITHUB_OUTPUT
          
  trigger-workflow:
    needs: get-targets
    uses: CallumWalley/mkdocs-demo-deploy/.github/workflows/deploy.yml@main
    with: 
      use-cache: false
      targets: ${{ needs.get-targets.outputs.targets }}
