name: Clear Cache
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
env:
  PROD_REPO: nesi/support-docs
  GH_TOKEN: ${{ github.token }}
jobs: 
  get-branches:
    outputs:
      branches: ${{ steps.get-branches.outputs.branches }}
    runs-on: ubuntu-latest
    steps:
    - name: Get active PR Branches
      id: get-branches
      run: |
          branches="$(for pr in $(gh pr list --repo ${PROD_REPO} --json headRefName | jq -r '.[].headRefName'); do printf "${pr} "; done)"
          echo "info:: title=Open Valid Merge Requests" :: ${branches}
          echo "branches=$branches" >> $GITHUB_OUTPUT
  trigger-workflow:
    needs: get-branches
    uses: CallumWalley/support-docs-dev/.github/workflows/deploy.yml@main
    with: 
      use-cache: false
      pr-branches: ${{ needs.get-branches.outputs.branches }}
