name: Clear Cache
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
env:
  PROD_REPOS: nesi/support-docs nesi/research-developer-cloud
  GH_TOKEN: ${{ github.token }}
jobs: 
  get-targets:
    outputs:
      alltargets: ${{ steps.get-targets.outputs.alltargets }}
    runs-on: ubuntu-latest
    steps:
    - name: Get active PR Branches
      id: get-targets
      run: |
          alltargets=""
          for repo in $PROD_REPOS;do
            branches="$(for pr in $(gh pr list --repo ${repo} --json headRefName | jq -r '.[].headRefName'); do printf "${pr} "; done)"
            echo "::notice:: Open Valid Merge Requests in ${repo}: ${branches}"
            for branch in ${branches};do alltargets="${alltargets} ${repo}:${branch}";done
          done
          echo "alltargets=${alltargets}" >> $GITHUB_OUTPUT
          
  trigger-workflow:
    needs: get-targets
    uses: CallumWalley/support-docs-dev/.github/workflows/deploy.yml@main
    with: 
      use-cache: false
      pr-branches: ${{ needs.get-targets.outputs.targets }}
