name: Deploy to gh-pages 
on:
  repository_dispatch:
    types: deploy
  workflow_dispatch:
    inputs:
      pr-branches:
        description: List of branches to deploy.
        type: text
env:
  MODULE_LIST_PATH: docs/assets/module-list.json
  PYTHON_VERSION: 3.x
  GH_TOKEN: ${{ github.token }}
  PROD_REPO: nesi/support-docs
permissions: write-all
jobs:
  documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.PROD_REPO }}
          # fetch-depth: 0
      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Set up build cache
        uses: actions/cache/restore@v4
        with:
          key: mkdocs-cache # mkdocs-${{ hashfiles('.cache/**') }}
          path: ./*
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Create dev sub-deployments
        run: |
            mkdir public
            for pr in ${{ github.event.client_payload.pr-branches || inputs.pr-branches }}; do                
                git checkout origin/$pr || ( echo "Failed to checkout ${pr}"; continue )
                mkdocs build --dirty --quiet --site-dir public/$pr 
            done
      - name: Adjust permissions
        run: |
          chmod -c -R +rX public/ | while read line; do
            echo "::info title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      - name: Save build cache
        uses: actions/cache/save@v4
        with:
          key: mkdocs-cache # mkdocs-${{ hashfiles('.cache/**') }}
          path: ./*
      # - name: Post Cmment to PR
      #   run: |
      #     for pr in ${{ github.event.client_payload.pr-branches || inputs.pr-branches }}; do                
      #         msg="Test deployment available at <a href=\"${DEPLOY_URL}/${pr}\">${DEPLOY_URL}/${pr}</a>"
      #         gh pr view ${pr} -R ${PROD_REPO}
      #         gh pr comment ${pr} --body "${msg}" -R ${PROD_REPO}   
      #         (gh pr comment ${pr} --edit-last --body "${msg}" -R ${PROD_REPO}) || (gh pr comment ${pr} --body "${msg}" -R ${PROD_REPO})
      # done
          
